/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjetsIndexRouteImport } from './routes/projets.index'
import { Route as ProjetsNouveauRouteImport } from './routes/projets.nouveau'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsIndexRoute = ProjetsIndexRouteImport.update({
  id: '/projets/',
  path: '/projets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsNouveauRoute = ProjetsNouveauRouteImport.update({
  id: '/projets/nouveau',
  path: '/projets/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projets/nouveau': typeof ProjetsNouveauRoute
  '/projets/': typeof ProjetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projets/nouveau': typeof ProjetsNouveauRoute
  '/projets': typeof ProjetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projets/nouveau': typeof ProjetsNouveauRoute
  '/projets/': typeof ProjetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/projets/nouveau' | '/projets/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/projets/nouveau' | '/projets'
  id: '__root__' | '/' | '/login' | '/projets/nouveau' | '/projets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProjetsNouveauRoute: typeof ProjetsNouveauRoute
  ProjetsIndexRoute: typeof ProjetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/': {
      id: '/projets/'
      path: '/projets'
      fullPath: '/projets/'
      preLoaderRoute: typeof ProjetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/nouveau': {
      id: '/projets/nouveau'
      path: '/projets/nouveau'
      fullPath: '/projets/nouveau'
      preLoaderRoute: typeof ProjetsNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProjetsNouveauRoute: ProjetsNouveauRoute,
  ProjetsIndexRoute: ProjetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
