/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelesRouteImport } from './routes/modeles'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as ProjetsIndexRouteImport } from './routes/projets.index'
import { Route as ProjetsProjectIdRouteImport } from './routes/projets.$projectId'
import { Route as ProjetsNouveauRouteImport } from './routes/projets.nouveau'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelesRoute = ModelesRouteImport.update({
  id: '/modeles',
  path: '/modeles',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsIndexRoute = ProjetsIndexRouteImport.update({
  id: '/projets/',
  path: '/projets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsProjectIdRoute = ProjetsProjectIdRouteImport.update({
  id: '/projets/$projectId',
  path: '/projets/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsNouveauRoute = ProjetsNouveauRouteImport.update({
  id: '/projets/nouveau',
  path: '/projets/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historique': typeof HistoriqueRoute
  '/login': typeof LoginRoute
  '/modeles': typeof ModelesRoute
  '/parametres': typeof ParametresRoute
  '/projets/$projectId': typeof ProjetsProjectIdRoute
  '/projets/nouveau': typeof ProjetsNouveauRoute
  '/projets/': typeof ProjetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historique': typeof HistoriqueRoute
  '/login': typeof LoginRoute
  '/modeles': typeof ModelesRoute
  '/parametres': typeof ParametresRoute
  '/projets/$projectId': typeof ProjetsProjectIdRoute
  '/projets/nouveau': typeof ProjetsNouveauRoute
  '/projets': typeof ProjetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historique': typeof HistoriqueRoute
  '/login': typeof LoginRoute
  '/modeles': typeof ModelesRoute
  '/parametres': typeof ParametresRoute
  '/projets/$projectId': typeof ProjetsProjectIdRoute
  '/projets/nouveau': typeof ProjetsNouveauRoute
  '/projets/': typeof ProjetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/historique'
    | '/login'
    | '/modeles'
    | '/parametres'
    | '/projets/$projectId'
    | '/projets/nouveau'
    | '/projets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/historique'
    | '/login'
    | '/modeles'
    | '/parametres'
    | '/projets/$projectId'
    | '/projets/nouveau'
    | '/projets'
  id:
    | '__root__'
    | '/'
    | '/historique'
    | '/login'
    | '/modeles'
    | '/parametres'
    | '/projets/$projectId'
    | '/projets/nouveau'
    | '/projets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoriqueRoute: typeof HistoriqueRoute
  LoginRoute: typeof LoginRoute
  ModelesRoute: typeof ModelesRoute
  ParametresRoute: typeof ParametresRoute
  ProjetsProjectIdRoute: typeof ProjetsProjectIdRoute
  ProjetsNouveauRoute: typeof ProjetsNouveauRoute
  ProjetsIndexRoute: typeof ProjetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modeles': {
      id: '/modeles'
      path: '/modeles'
      fullPath: '/modeles'
      preLoaderRoute: typeof ModelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/': {
      id: '/projets/'
      path: '/projets'
      fullPath: '/projets/'
      preLoaderRoute: typeof ProjetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/$projectId': {
      id: '/projets/$projectId'
      path: '/projets/$projectId'
      fullPath: '/projets/$projectId'
      preLoaderRoute: typeof ProjetsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/nouveau': {
      id: '/projets/nouveau'
      path: '/projets/nouveau'
      fullPath: '/projets/nouveau'
      preLoaderRoute: typeof ProjetsNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoriqueRoute: HistoriqueRoute,
  LoginRoute: LoginRoute,
  ModelesRoute: ModelesRoute,
  ParametresRoute: ParametresRoute,
  ProjetsProjectIdRoute: ProjetsProjectIdRoute,
  ProjetsNouveauRoute: ProjetsNouveauRoute,
  ProjetsIndexRoute: ProjetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
